# Generated by Django 4.0.6 on 2022-07-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_alter_mymodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel1',
            name='name',
            field=models.TextField(verbose_name='описание'),
        ),
    ]
