# Generated by Django 4.0.6 on 2022-07-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_mymodel1_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mymodel',
            new_name='Название_описание',
        ),
    ]
