# Generated by Django 4.0.6 on 2022-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_cимптом_диагностика_лечение_препарат_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Болезни',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('description1', models.TextField(verbose_name='Причин_возникновения')),
                ('description2', models.TextField(verbose_name='Cимптом')),
                ('description3', models.TextField(verbose_name='Диагностика')),
                ('description4', models.TextField(verbose_name='Лечение')),
                ('description5', models.TextField(verbose_name='Препарат')),
            ],
        ),
        migrations.DeleteModel(
            name='Cимптом',
        ),
        migrations.DeleteModel(
            name='Диагностика',
        ),
        migrations.DeleteModel(
            name='Лечение',
        ),
        migrations.DeleteModel(
            name='Название_описание',
        ),
        migrations.DeleteModel(
            name='Препарат',
        ),
        migrations.DeleteModel(
            name='Причин_возникновения',
        ),
    ]
