# Generated by Django 4.0.6 on 2022-07-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_remove_болезни_description5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mymodel1',
            new_name='Лекарства',
        ),
    ]
