# Generated by Django 4.0.6 on 2022-07-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_rename_mymodel1_лекарства'),
    ]

    operations = [
        migrations.RenameField(
            model_name='болезни',
            old_name='description2',
            new_name='Cимптом',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='description3',
            new_name='Диагностика',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='description4',
            new_name='Лечение',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='description1',
            new_name='Причин_возникновения',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='title',
            new_name='название',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='description',
            new_name='описание',
        ),
        migrations.RenameField(
            model_name='лекарства',
            old_name='instruction',
            new_name='инструкция',
        ),
        migrations.RenameField(
            model_name='лекарства',
            old_name='name',
            new_name='описание',
        ),
        migrations.RenameField(
            model_name='лекарства',
            old_name='character',
            new_name='характеристика',
        ),
    ]
