# Generated by Django 4.0.6 on 2022-07-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_rename_description2_болезни_cимптом_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='болезни',
            old_name='описание',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='Причин_возникновения',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='Cимптом',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='Диагностика',
            new_name='description3',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='Лечение',
            new_name='description4',
        ),
        migrations.RenameField(
            model_name='болезни',
            old_name='название',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='лекарства',
            old_name='характеристика',
            new_name='character',
        ),
        migrations.RenameField(
            model_name='лекарства',
            old_name='инструкция',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='лекарства',
            old_name='описание',
            new_name='name',
        ),
    ]
