# Generated by Django 4.0.6 on 2022-08-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_rename_описание_болезни_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davolanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davvolanish', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostika', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kasalikk_sabablari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasallik_sabablari', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kasallik_asoratlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasallik_asoratlari', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kasallik_haqida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasallik_haqida', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kassalik_nomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasallik_nomi', models.TextField()),
            ],
        ),
    ]
