# Generated by Django 4.0.6 on 2022-08-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_davolanish_diagnostika_kasalikk_sabablari_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kassalik_nomi',
            new_name='Kasalik_nomi',
        ),
    ]
