# Generated by Django 4.0.6 on 2022-08-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_rename_kassalik_nomi_kasalik_nomi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kasalik_nomi',
            new_name='Kasallik_nomi',
        ),
    ]
