# Generated by Django 4.0.6 on 2022-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_rename_kasalik_nomi_kasallik_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Болезни1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('description1', models.TextField(verbose_name='Причин_возникновения')),
                ('description2', models.TextField(verbose_name='Cимптом')),
                ('description3', models.TextField(verbose_name='Диагностика')),
                ('description4', models.TextField(verbose_name='Лечение')),
            ],
        ),
        migrations.CreateModel(
            name='Лекарства1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='описание')),
                ('character', models.TextField(verbose_name='характеристика')),
                ('instruction', models.TextField(verbose_name='инструкция')),
            ],
        ),
    ]
